/* ------------------------------------------------------------------
   Official Lok Sabha (parliamentary) constituencies — all of India.

   Source: Election Commission of India delimitation (543 PCs), with the
   post-delimitation reorganisation applied so state grouping is current:
   Telangana split from Andhra Pradesh, and Ladakh separated from Jammu &
   Kashmir. Used as the single source of truth for the constituency a
   citizen picks on Raise-your-voice AND the constituency an admin assigns
   to an MP — so a voice always routes to exactly one MP dashboard.
   ------------------------------------------------------------------ */

export type Constituency = { no: number; name: string; state: string };

/** All 543 Lok Sabha constituencies, sorted by state then constituency no. */
export const CONSTITUENCIES: Constituency[] = [
  { no: 1, name: "Andaman & Nicobar Islands", state: "Andaman & Nicobar Islands" },
  { no: 18, name: "Araku", state: "Andhra Pradesh" },
  { no: 19, name: "Srikakulam", state: "Andhra Pradesh" },
  { no: 20, name: "Vizianagaram", state: "Andhra Pradesh" },
  { no: 21, name: "Visakhapatnam", state: "Andhra Pradesh" },
  { no: 22, name: "Anakapalli", state: "Andhra Pradesh" },
  { no: 23, name: "Kakinada", state: "Andhra Pradesh" },
  { no: 24, name: "Amlapuram", state: "Andhra Pradesh" },
  { no: 25, name: "Rajahmundry", state: "Andhra Pradesh" },
  { no: 26, name: "Narsapuram", state: "Andhra Pradesh" },
  { no: 27, name: "Eluru", state: "Andhra Pradesh" },
  { no: 28, name: "Machilipatnam", state: "Andhra Pradesh" },
  { no: 29, name: "Vijayawada", state: "Andhra Pradesh" },
  { no: 30, name: "Guntur", state: "Andhra Pradesh" },
  { no: 31, name: "Narasaraopet", state: "Andhra Pradesh" },
  { no: 32, name: "Bapatla", state: "Andhra Pradesh" },
  { no: 33, name: "Ongole", state: "Andhra Pradesh" },
  { no: 34, name: "Nandyal", state: "Andhra Pradesh" },
  { no: 35, name: "Kurnool", state: "Andhra Pradesh" },
  { no: 36, name: "Anantapur", state: "Andhra Pradesh" },
  { no: 37, name: "Hindupur", state: "Andhra Pradesh" },
  { no: 38, name: "Kadapa", state: "Andhra Pradesh" },
  { no: 39, name: "Nellore", state: "Andhra Pradesh" },
  { no: 40, name: "Tirupati", state: "Andhra Pradesh" },
  { no: 41, name: "Rajampet", state: "Andhra Pradesh" },
  { no: 42, name: "Chittoor", state: "Andhra Pradesh" },
  { no: 1, name: "Arunachal West", state: "Arunachal Pradesh" },
  { no: 2, name: "Arunachal East", state: "Arunachal Pradesh" },
  { no: 1, name: "Karimganj", state: "Assam" },
  { no: 2, name: "Silchar", state: "Assam" },
  { no: 3, name: "Autonomous District", state: "Assam" },
  { no: 4, name: "Dhubri", state: "Assam" },
  { no: 5, name: "Kokrajhar", state: "Assam" },
  { no: 6, name: "Barpeta", state: "Assam" },
  { no: 7, name: "Guwahati", state: "Assam" },
  { no: 8, name: "Mangaldoi", state: "Assam" },
  { no: 9, name: "Tezpur", state: "Assam" },
  { no: 10, name: "Nagaon", state: "Assam" },
  { no: 11, name: "Kaliabor", state: "Assam" },
  { no: 12, name: "Jorhat", state: "Assam" },
  { no: 13, name: "Dibrugarh", state: "Assam" },
  { no: 14, name: "Lakhimpur", state: "Assam" },
  { no: 1, name: "Valmiki Nagar", state: "Bihar" },
  { no: 2, name: "Pashchim Champaran", state: "Bihar" },
  { no: 3, name: "Purba Champaran", state: "Bihar" },
  { no: 4, name: "Sheohar", state: "Bihar" },
  { no: 5, name: "Sitamarhi", state: "Bihar" },
  { no: 6, name: "Madhubani", state: "Bihar" },
  { no: 7, name: "Jhanjharpur", state: "Bihar" },
  { no: 8, name: "Supaul", state: "Bihar" },
  { no: 9, name: "Araria", state: "Bihar" },
  { no: 10, name: "Kishanganj", state: "Bihar" },
  { no: 11, name: "Katihar", state: "Bihar" },
  { no: 12, name: "Purnia", state: "Bihar" },
  { no: 13, name: "Madhepura", state: "Bihar" },
  { no: 14, name: "Darbhanga", state: "Bihar" },
  { no: 15, name: "Muzaffarpur", state: "Bihar" },
  { no: 16, name: "Vaishali", state: "Bihar" },
  { no: 17, name: "Gopalganj", state: "Bihar" },
  { no: 18, name: "Siwan", state: "Bihar" },
  { no: 19, name: "Maharajganj", state: "Bihar" },
  { no: 20, name: "Saran (Chhapra)", state: "Bihar" },
  { no: 21, name: "Hajipur", state: "Bihar" },
  { no: 22, name: "Ujiapur", state: "Bihar" },
  { no: 23, name: "Samastipur", state: "Bihar" },
  { no: 24, name: "Begusarai", state: "Bihar" },
  { no: 25, name: "Khagaria", state: "Bihar" },
  { no: 26, name: "Bhagalpur", state: "Bihar" },
  { no: 27, name: "Banka", state: "Bihar" },
  { no: 28, name: "Munger", state: "Bihar" },
  { no: 29, name: "Nalanda", state: "Bihar" },
  { no: 30, name: "Patna Sahib", state: "Bihar" },
  { no: 31, name: "Pataliputra", state: "Bihar" },
  { no: 32, name: "Arrah", state: "Bihar" },
  { no: 33, name: "Buxar", state: "Bihar" },
  { no: 34, name: "Sasaram", state: "Bihar" },
  { no: 35, name: "Karakat", state: "Bihar" },
  { no: 36, name: "Jahanabad", state: "Bihar" },
  { no: 37, name: "Aurangabad", state: "Bihar" },
  { no: 38, name: "Gaya", state: "Bihar" },
  { no: 39, name: "Nawada", state: "Bihar" },
  { no: 40, name: "Jamui", state: "Bihar" },
  { no: 1, name: "Chandigarh", state: "Chandigarh" },
  { no: 1, name: "Surguja", state: "Chhattisgarh" },
  { no: 2, name: "Raigarh", state: "Chhattisgarh" },
  { no: 3, name: "Janjgir-Champa", state: "Chhattisgarh" },
  { no: 4, name: "Korba", state: "Chhattisgarh" },
  { no: 5, name: "Bilaspur", state: "Chhattisgarh" },
  { no: 6, name: "Rajnandgaon", state: "Chhattisgarh" },
  { no: 7, name: "Durg", state: "Chhattisgarh" },
  { no: 8, name: "Raipur", state: "Chhattisgarh" },
  { no: 9, name: "Mahasamund", state: "Chhattisgarh" },
  { no: 10, name: "Bastar", state: "Chhattisgarh" },
  { no: 11, name: "Kanker", state: "Chhattisgarh" },
  { no: 1, name: "Dadra & Nagar Haveli", state: "Dadra & Nagar Haveli" },
  { no: 1, name: "Daman & Diu", state: "Daman & Diu" },
  { no: 1, name: "Chandni Chowk", state: "Delhi" },
  { no: 2, name: "North East Delhi", state: "Delhi" },
  { no: 3, name: "East Delhi", state: "Delhi" },
  { no: 4, name: "New Delhi", state: "Delhi" },
  { no: 5, name: "North West Delhi", state: "Delhi" },
  { no: 6, name: "West Delhi", state: "Delhi" },
  { no: 7, name: "South Delhi", state: "Delhi" },
  { no: 1, name: "North Goa", state: "Goa" },
  { no: 2, name: "South Goa", state: "Goa" },
  { no: 1, name: "Kachchh", state: "Gujarat" },
  { no: 2, name: "Banas Kantha", state: "Gujarat" },
  { no: 3, name: "Patan", state: "Gujarat" },
  { no: 4, name: "Mahesana", state: "Gujarat" },
  { no: 5, name: "Sabar Kantha", state: "Gujarat" },
  { no: 6, name: "Gandhinagar", state: "Gujarat" },
  { no: 7, name: "Ahmadabad (East)", state: "Gujarat" },
  { no: 8, name: "Ahmadabad (West)", state: "Gujarat" },
  { no: 9, name: "Surendranagar", state: "Gujarat" },
  { no: 10, name: "Rajkot", state: "Gujarat" },
  { no: 11, name: "Porbandar", state: "Gujarat" },
  { no: 12, name: "Jamnagar", state: "Gujarat" },
  { no: 13, name: "Junagadh", state: "Gujarat" },
  { no: 14, name: "Amreli", state: "Gujarat" },
  { no: 15, name: "Bhavnagar", state: "Gujarat" },
  { no: 16, name: "Anand", state: "Gujarat" },
  { no: 17, name: "Kheda", state: "Gujarat" },
  { no: 18, name: "Panch Mahals", state: "Gujarat" },
  { no: 19, name: "Dohad", state: "Gujarat" },
  { no: 20, name: "Vadodara", state: "Gujarat" },
  { no: 21, name: "Chhota Udaipur", state: "Gujarat" },
  { no: 22, name: "Bharuch", state: "Gujarat" },
  { no: 23, name: "Bardoli", state: "Gujarat" },
  { no: 24, name: "Surat", state: "Gujarat" },
  { no: 25, name: "Navsari", state: "Gujarat" },
  { no: 26, name: "Valsad", state: "Gujarat" },
  { no: 1, name: "Ambala", state: "Haryana" },
  { no: 2, name: "Krukshetra", state: "Haryana" },
  { no: 3, name: "Sirsa", state: "Haryana" },
  { no: 4, name: "Hisar", state: "Haryana" },
  { no: 5, name: "Karnal", state: "Haryana" },
  { no: 6, name: "Sonipat", state: "Haryana" },
  { no: 7, name: "Rohtak", state: "Haryana" },
  { no: 8, name: "Bhiwani - Mahendragarh", state: "Haryana" },
  { no: 9, name: "Gurgaon", state: "Haryana" },
  { no: 10, name: "Faridabad", state: "Haryana" },
  { no: 1, name: "Kangra", state: "Himachal Pradesh" },
  { no: 2, name: "Mandi", state: "Himachal Pradesh" },
  { no: 3, name: "Hamirpur", state: "Himachal Pradesh" },
  { no: 4, name: "Shimla", state: "Himachal Pradesh" },
  { no: 1, name: "Baramula", state: "Jammu & Kashmir" },
  { no: 2, name: "Srinagar", state: "Jammu & Kashmir" },
  { no: 3, name: "Anantnag", state: "Jammu & Kashmir" },
  { no: 5, name: "Udhampur", state: "Jammu & Kashmir" },
  { no: 6, name: "Jammu", state: "Jammu & Kashmir" },
  { no: 1, name: "Rajmahal", state: "Jharkhand" },
  { no: 2, name: "Dumka", state: "Jharkhand" },
  { no: 3, name: "Godda", state: "Jharkhand" },
  { no: 4, name: "Chatra", state: "Jharkhand" },
  { no: 5, name: "Kodarma", state: "Jharkhand" },
  { no: 6, name: "Giridih", state: "Jharkhand" },
  { no: 7, name: "Dhanbad", state: "Jharkhand" },
  { no: 8, name: "Ranchi", state: "Jharkhand" },
  { no: 9, name: "Jamshedpur", state: "Jharkhand" },
  { no: 10, name: "Singhbhum", state: "Jharkhand" },
  { no: 11, name: "Khunti", state: "Jharkhand" },
  { no: 12, name: "Lohardaga", state: "Jharkhand" },
  { no: 13, name: "Palamu", state: "Jharkhand" },
  { no: 14, name: "Hazaribagh", state: "Jharkhand" },
  { no: 1, name: "Chikkodi", state: "Karnataka" },
  { no: 2, name: "Belgaum", state: "Karnataka" },
  { no: 3, name: "Bagalkot", state: "Karnataka" },
  { no: 4, name: "Bijapur", state: "Karnataka" },
  { no: 5, name: "Gulbarga", state: "Karnataka" },
  { no: 6, name: "Raichur", state: "Karnataka" },
  { no: 7, name: "Bidar", state: "Karnataka" },
  { no: 8, name: "Koppal", state: "Karnataka" },
  { no: 9, name: "Bellary", state: "Karnataka" },
  { no: 10, name: "Haveri", state: "Karnataka" },
  { no: 11, name: "Dharwad", state: "Karnataka" },
  { no: 12, name: "Uttara Kannada", state: "Karnataka" },
  { no: 13, name: "Davanagere", state: "Karnataka" },
  { no: 14, name: "Shimoga", state: "Karnataka" },
  { no: 15, name: "Udupi Chikmagalur", state: "Karnataka" },
  { no: 16, name: "Hassan", state: "Karnataka" },
  { no: 17, name: "Dakshina Kannada", state: "Karnataka" },
  { no: 18, name: "Chitradurga", state: "Karnataka" },
  { no: 19, name: "Tumkur", state: "Karnataka" },
  { no: 20, name: "Mandya", state: "Karnataka" },
  { no: 21, name: "Mysore", state: "Karnataka" },
  { no: 22, name: "Chamrajnagar", state: "Karnataka" },
  { no: 23, name: "Bangalore Rural", state: "Karnataka" },
  { no: 24, name: "Bangalore North", state: "Karnataka" },
  { no: 25, name: "Bangalore Central", state: "Karnataka" },
  { no: 26, name: "Bangalore South", state: "Karnataka" },
  { no: 27, name: "Chikkaballapura", state: "Karnataka" },
  { no: 28, name: "Kolar", state: "Karnataka" },
  { no: 1, name: "Kasaragod", state: "Kerala" },
  { no: 2, name: "Kannur", state: "Kerala" },
  { no: 3, name: "Vadakara", state: "Kerala" },
  { no: 4, name: "Wayanad", state: "Kerala" },
  { no: 5, name: "Kozhikode", state: "Kerala" },
  { no: 6, name: "Malappuram", state: "Kerala" },
  { no: 7, name: "Ponnani", state: "Kerala" },
  { no: 8, name: "Palakkad", state: "Kerala" },
  { no: 9, name: "Alathur", state: "Kerala" },
  { no: 10, name: "Thrissur", state: "Kerala" },
  { no: 11, name: "Chalakudy", state: "Kerala" },
  { no: 12, name: "Ernakulam", state: "Kerala" },
  { no: 13, name: "Idukki", state: "Kerala" },
  { no: 14, name: "Kottayam", state: "Kerala" },
  { no: 15, name: "Alappuzha", state: "Kerala" },
  { no: 16, name: "Mavelikkara", state: "Kerala" },
  { no: 17, name: "Pathanamthitta", state: "Kerala" },
  { no: 18, name: "Kollam", state: "Kerala" },
  { no: 19, name: "Attingal", state: "Kerala" },
  { no: 20, name: "Thiruvananthapuram", state: "Kerala" },
  { no: 4, name: "Leh (Ladakh)", state: "Ladakh" },
  { no: 1, name: "Lakshadweep", state: "Lakshadweep" },
  { no: 1, name: "Morena", state: "Madhya Pradesh" },
  { no: 2, name: "Bhind", state: "Madhya Pradesh" },
  { no: 3, name: "Gwalior", state: "Madhya Pradesh" },
  { no: 4, name: "Guna", state: "Madhya Pradesh" },
  { no: 5, name: "Sagar", state: "Madhya Pradesh" },
  { no: 6, name: "Tikamgarh", state: "Madhya Pradesh" },
  { no: 7, name: "Damoh", state: "Madhya Pradesh" },
  { no: 8, name: "Khajuraho", state: "Madhya Pradesh" },
  { no: 9, name: "Satna", state: "Madhya Pradesh" },
  { no: 10, name: "Rewa", state: "Madhya Pradesh" },
  { no: 11, name: "Sidhi", state: "Madhya Pradesh" },
  { no: 12, name: "Shahdol", state: "Madhya Pradesh" },
  { no: 13, name: "Jabalpur", state: "Madhya Pradesh" },
  { no: 14, name: "Mandla", state: "Madhya Pradesh" },
  { no: 15, name: "Balaghat", state: "Madhya Pradesh" },
  { no: 16, name: "Chhindwara", state: "Madhya Pradesh" },
  { no: 17, name: "Hoshangabad", state: "Madhya Pradesh" },
  { no: 18, name: "Vidisha", state: "Madhya Pradesh" },
  { no: 19, name: "Bhopal", state: "Madhya Pradesh" },
  { no: 20, name: "Rajgarh", state: "Madhya Pradesh" },
  { no: 21, name: "Dewas", state: "Madhya Pradesh" },
  { no: 22, name: "Ujjain", state: "Madhya Pradesh" },
  { no: 23, name: "Mandsaur", state: "Madhya Pradesh" },
  { no: 24, name: "Ratlam", state: "Madhya Pradesh" },
  { no: 25, name: "Dhar", state: "Madhya Pradesh" },
  { no: 26, name: "Indore", state: "Madhya Pradesh" },
  { no: 27, name: "Khargone", state: "Madhya Pradesh" },
  { no: 28, name: "Khandwa", state: "Madhya Pradesh" },
  { no: 29, name: "Betul", state: "Madhya Pradesh" },
  { no: 1, name: "Nandurbar", state: "Maharashtra" },
  { no: 2, name: "Dhule", state: "Maharashtra" },
  { no: 3, name: "Jalgaon", state: "Maharashtra" },
  { no: 4, name: "Raver", state: "Maharashtra" },
  { no: 5, name: "Buldana", state: "Maharashtra" },
  { no: 6, name: "Akola", state: "Maharashtra" },
  { no: 7, name: "Amravati", state: "Maharashtra" },
  { no: 8, name: "Wardha", state: "Maharashtra" },
  { no: 9, name: "Ramtek", state: "Maharashtra" },
  { no: 10, name: "Nagpur", state: "Maharashtra" },
  { no: 11, name: "Bhandara - Gondiya", state: "Maharashtra" },
  { no: 12, name: "Garhchiroli - Chimur", state: "Maharashtra" },
  { no: 13, name: "Chandrapur", state: "Maharashtra" },
  { no: 14, name: "Yavatmal - Washim", state: "Maharashtra" },
  { no: 15, name: "Hingoli", state: "Maharashtra" },
  { no: 16, name: "Nanded", state: "Maharashtra" },
  { no: 17, name: "Parbhani", state: "Maharashtra" },
  { no: 18, name: "Jalna", state: "Maharashtra" },
  { no: 19, name: "Aurangabad", state: "Maharashtra" },
  { no: 20, name: "Dindori", state: "Maharashtra" },
  { no: 21, name: "Nashik", state: "Maharashtra" },
  { no: 22, name: "Palghar", state: "Maharashtra" },
  { no: 23, name: "Biwandi", state: "Maharashtra" },
  { no: 24, name: "Kalyan", state: "Maharashtra" },
  { no: 25, name: "Thane", state: "Maharashtra" },
  { no: 26, name: "Mumbai North", state: "Maharashtra" },
  { no: 27, name: "Mumbai North-West", state: "Maharashtra" },
  { no: 28, name: "Mumbai North-East", state: "Maharashtra" },
  { no: 29, name: "Mumbai North-Central", state: "Maharashtra" },
  { no: 30, name: "Mumbai South-Central", state: "Maharashtra" },
  { no: 31, name: "Mumbai South", state: "Maharashtra" },
  { no: 32, name: "Raigarh", state: "Maharashtra" },
  { no: 33, name: "Maval", state: "Maharashtra" },
  { no: 34, name: "Pune", state: "Maharashtra" },
  { no: 35, name: "Baramati", state: "Maharashtra" },
  { no: 36, name: "Shirur", state: "Maharashtra" },
  { no: 37, name: "Ahmadnagar", state: "Maharashtra" },
  { no: 38, name: "Shirdi", state: "Maharashtra" },
  { no: 39, name: "Beed", state: "Maharashtra" },
  { no: 40, name: "Osmanabad", state: "Maharashtra" },
  { no: 41, name: "Latur", state: "Maharashtra" },
  { no: 42, name: "Solapur", state: "Maharashtra" },
  { no: 43, name: "Madha", state: "Maharashtra" },
  { no: 44, name: "Sangli", state: "Maharashtra" },
  { no: 45, name: "Satara", state: "Maharashtra" },
  { no: 46, name: "Ratnagiri - Sindhudurg", state: "Maharashtra" },
  { no: 47, name: "Kolhapur", state: "Maharashtra" },
  { no: 48, name: "Hatkanangle", state: "Maharashtra" },
  { no: 1, name: "Inner Manipur", state: "Manipur" },
  { no: 2, name: "Outer Manipur", state: "Manipur" },
  { no: 1, name: "Shillong", state: "Meghalaya" },
  { no: 2, name: "Tura", state: "Meghalaya" },
  { no: 1, name: "Mizoram", state: "Mizoram" },
  { no: 1, name: "Nagaland", state: "Nagaland" },
  { no: 1, name: "Bargarh", state: "Odisha" },
  { no: 2, name: "Sundargarh", state: "Odisha" },
  { no: 3, name: "Sambalpur", state: "Odisha" },
  { no: 4, name: "Kendujhar", state: "Odisha" },
  { no: 5, name: "Mayurbhanj", state: "Odisha" },
  { no: 6, name: "Baleshwar", state: "Odisha" },
  { no: 7, name: "Bhadrak", state: "Odisha" },
  { no: 8, name: "Jajapur", state: "Odisha" },
  { no: 9, name: "Dhenkanal", state: "Odisha" },
  { no: 10, name: "Bolangir", state: "Odisha" },
  { no: 11, name: "Kalahandi", state: "Odisha" },
  { no: 12, name: "Nabarangapur", state: "Odisha" },
  { no: 13, name: "Kandhamal", state: "Odisha" },
  { no: 14, name: "Cuttack", state: "Odisha" },
  { no: 15, name: "Kendrapara", state: "Odisha" },
  { no: 16, name: "Jagatsinghpur", state: "Odisha" },
  { no: 17, name: "Puri", state: "Odisha" },
  { no: 18, name: "Bhubaneswar", state: "Odisha" },
  { no: 19, name: "Aska", state: "Odisha" },
  { no: 20, name: "Berhampur", state: "Odisha" },
  { no: 21, name: "Koraput", state: "Odisha" },
  { no: 1, name: "Puducherry", state: "Puducherry" },
  { no: 1, name: "Gurdaspur", state: "Punjab" },
  { no: 2, name: "Amritsar", state: "Punjab" },
  { no: 3, name: "Khadoor Sahib", state: "Punjab" },
  { no: 4, name: "Jalandhar", state: "Punjab" },
  { no: 5, name: "Hoshiarpur", state: "Punjab" },
  { no: 6, name: "Anandpur Sahib", state: "Punjab" },
  { no: 7, name: "Ludhiana", state: "Punjab" },
  { no: 8, name: "Fatehgarh Sahib", state: "Punjab" },
  { no: 9, name: "Faridkot", state: "Punjab" },
  { no: 10, name: "Firozpur", state: "Punjab" },
  { no: 11, name: "Bathinda", state: "Punjab" },
  { no: 12, name: "Sangrur", state: "Punjab" },
  { no: 13, name: "Patiala", state: "Punjab" },
  { no: 1, name: "Ganganagar", state: "Rajasthan" },
  { no: 2, name: "Bikaner", state: "Rajasthan" },
  { no: 3, name: "Churu", state: "Rajasthan" },
  { no: 4, name: "Jhunjhunun", state: "Rajasthan" },
  { no: 5, name: "Sikar", state: "Rajasthan" },
  { no: 6, name: "Jaipur Rural", state: "Rajasthan" },
  { no: 7, name: "Jaipur", state: "Rajasthan" },
  { no: 8, name: "Alwar", state: "Rajasthan" },
  { no: 9, name: "Bharatpur", state: "Rajasthan" },
  { no: 10, name: "Karauli - Dhaulpur", state: "Rajasthan" },
  { no: 11, name: "Dausa", state: "Rajasthan" },
  { no: 12, name: "Tonk - Sawai Madhopur", state: "Rajasthan" },
  { no: 13, name: "Ajmer", state: "Rajasthan" },
  { no: 14, name: "Nagaur", state: "Rajasthan" },
  { no: 15, name: "Pali", state: "Rajasthan" },
  { no: 16, name: "Jodhpur", state: "Rajasthan" },
  { no: 17, name: "Barmer", state: "Rajasthan" },
  { no: 18, name: "Jalore", state: "Rajasthan" },
  { no: 19, name: "Udaipur", state: "Rajasthan" },
  { no: 20, name: "Banswara", state: "Rajasthan" },
  { no: 21, name: "Chittaurgarh", state: "Rajasthan" },
  { no: 22, name: "Rajsamand", state: "Rajasthan" },
  { no: 23, name: "Bhilwara", state: "Rajasthan" },
  { no: 24, name: "Kota", state: "Rajasthan" },
  { no: 25, name: "Jhalawar - Baran", state: "Rajasthan" },
  { no: 1, name: "Sikkim", state: "Sikkim" },
  { no: 1, name: "Tiruvallur", state: "Tamil Nadu" },
  { no: 2, name: "Chennai North", state: "Tamil Nadu" },
  { no: 3, name: "Chennai South", state: "Tamil Nadu" },
  { no: 4, name: "Chennai Central", state: "Tamil Nadu" },
  { no: 5, name: "Sriperumbudur", state: "Tamil Nadu" },
  { no: 6, name: "Kancheepuram", state: "Tamil Nadu" },
  { no: 7, name: "Arakkonam", state: "Tamil Nadu" },
  { no: 8, name: "Vellore", state: "Tamil Nadu" },
  { no: 9, name: "Krishnagiri", state: "Tamil Nadu" },
  { no: 10, name: "Dharmapuri", state: "Tamil Nadu" },
  { no: 11, name: "Tiruvannamalai", state: "Tamil Nadu" },
  { no: 12, name: "Arani", state: "Tamil Nadu" },
  { no: 13, name: "Viluppuram", state: "Tamil Nadu" },
  { no: 14, name: "Kallakurichi", state: "Tamil Nadu" },
  { no: 15, name: "Salem", state: "Tamil Nadu" },
  { no: 16, name: "Namakkal", state: "Tamil Nadu" },
  { no: 17, name: "Erode", state: "Tamil Nadu" },
  { no: 18, name: "Tiruppur", state: "Tamil Nadu" },
  { no: 19, name: "Nilgiris", state: "Tamil Nadu" },
  { no: 20, name: "Coimbatore", state: "Tamil Nadu" },
  { no: 21, name: "Pollachi", state: "Tamil Nadu" },
  { no: 22, name: "Dindigul", state: "Tamil Nadu" },
  { no: 23, name: "Karur", state: "Tamil Nadu" },
  { no: 24, name: "Tiruchirappalli", state: "Tamil Nadu" },
  { no: 25, name: "Perambalur", state: "Tamil Nadu" },
  { no: 26, name: "Cuddalore", state: "Tamil Nadu" },
  { no: 27, name: "Chidambaram", state: "Tamil Nadu" },
  { no: 28, name: "Mayiladuthurai", state: "Tamil Nadu" },
  { no: 29, name: "Nagappattinam", state: "Tamil Nadu" },
  { no: 30, name: "Thanjavur", state: "Tamil Nadu" },
  { no: 31, name: "Shivaganga", state: "Tamil Nadu" },
  { no: 32, name: "Madurai", state: "Tamil Nadu" },
  { no: 33, name: "Theni", state: "Tamil Nadu" },
  { no: 34, name: "Virudunagar", state: "Tamil Nadu" },
  { no: 35, name: "Ramanathapuram", state: "Tamil Nadu" },
  { no: 36, name: "Thoothukkudi", state: "Tamil Nadu" },
  { no: 37, name: "Tenkasi", state: "Tamil Nadu" },
  { no: 38, name: "Tirunelveli", state: "Tamil Nadu" },
  { no: 39, name: "Kanniyakumari", state: "Tamil Nadu" },
  { no: 1, name: "Adilabad", state: "Telangana" },
  { no: 2, name: "Peddapalle", state: "Telangana" },
  { no: 3, name: "Karimnagar", state: "Telangana" },
  { no: 4, name: "Nizamabad", state: "Telangana" },
  { no: 5, name: "Zahirabad", state: "Telangana" },
  { no: 6, name: "Medak", state: "Telangana" },
  { no: 7, name: "Malkajgiri", state: "Telangana" },
  { no: 8, name: "Secunderabad", state: "Telangana" },
  { no: 9, name: "Hyderabad", state: "Telangana" },
  { no: 10, name: "Chevella", state: "Telangana" },
  { no: 11, name: "Mahbubnagar", state: "Telangana" },
  { no: 12, name: "Nagarkurnool", state: "Telangana" },
  { no: 13, name: "Nalgonda", state: "Telangana" },
  { no: 14, name: "Bhongir", state: "Telangana" },
  { no: 15, name: "Warangal", state: "Telangana" },
  { no: 16, name: "Mahabubabad", state: "Telangana" },
  { no: 17, name: "Khammam", state: "Telangana" },
  { no: 1, name: "Tripura West", state: "Tripura" },
  { no: 2, name: "Tripura East", state: "Tripura" },
  { no: 1, name: "Saharanpur", state: "Uttar Pradesh" },
  { no: 2, name: "Kairana", state: "Uttar Pradesh" },
  { no: 3, name: "Muzaffarnagar", state: "Uttar Pradesh" },
  { no: 4, name: "Bijnor", state: "Uttar Pradesh" },
  { no: 5, name: "Nagina", state: "Uttar Pradesh" },
  { no: 6, name: "Moradabad", state: "Uttar Pradesh" },
  { no: 7, name: "Rampur", state: "Uttar Pradesh" },
  { no: 8, name: "Sambhal", state: "Uttar Pradesh" },
  { no: 9, name: "Amroha", state: "Uttar Pradesh" },
  { no: 10, name: "Meerut", state: "Uttar Pradesh" },
  { no: 11, name: "Baghpat", state: "Uttar Pradesh" },
  { no: 12, name: "Ghaziabad", state: "Uttar Pradesh" },
  { no: 13, name: "Gautam Buddha Nagar", state: "Uttar Pradesh" },
  { no: 14, name: "Bulandshahr", state: "Uttar Pradesh" },
  { no: 15, name: "Aligarh", state: "Uttar Pradesh" },
  { no: 16, name: "Hathras", state: "Uttar Pradesh" },
  { no: 17, name: "Mathura", state: "Uttar Pradesh" },
  { no: 18, name: "Agra", state: "Uttar Pradesh" },
  { no: 19, name: "Fatehpur Sikri", state: "Uttar Pradesh" },
  { no: 20, name: "Firozabad", state: "Uttar Pradesh" },
  { no: 21, name: "Mainpuri", state: "Uttar Pradesh" },
  { no: 22, name: "Etah", state: "Uttar Pradesh" },
  { no: 23, name: "Budaun", state: "Uttar Pradesh" },
  { no: 24, name: "Aonla", state: "Uttar Pradesh" },
  { no: 25, name: "Bareilly", state: "Uttar Pradesh" },
  { no: 26, name: "Pilibhit", state: "Uttar Pradesh" },
  { no: 27, name: "Shahjahanpur", state: "Uttar Pradesh" },
  { no: 28, name: "Kheri", state: "Uttar Pradesh" },
  { no: 29, name: "Dhaurahra", state: "Uttar Pradesh" },
  { no: 30, name: "Sitapur", state: "Uttar Pradesh" },
  { no: 31, name: "Hardoi", state: "Uttar Pradesh" },
  { no: 32, name: "Misrikh", state: "Uttar Pradesh" },
  { no: 33, name: "Unnao", state: "Uttar Pradesh" },
  { no: 34, name: "Mohanlalganj", state: "Uttar Pradesh" },
  { no: 35, name: "Lucknow", state: "Uttar Pradesh" },
  { no: 36, name: "Rae Bareli", state: "Uttar Pradesh" },
  { no: 37, name: "Amethi", state: "Uttar Pradesh" },
  { no: 38, name: "Sultanpur", state: "Uttar Pradesh" },
  { no: 39, name: "Pratapgarh", state: "Uttar Pradesh" },
  { no: 40, name: "Farrukhabad", state: "Uttar Pradesh" },
  { no: 41, name: "Etawah", state: "Uttar Pradesh" },
  { no: 42, name: "Kannauj", state: "Uttar Pradesh" },
  { no: 43, name: "Kanpur", state: "Uttar Pradesh" },
  { no: 44, name: "Akbarpur", state: "Uttar Pradesh" },
  { no: 45, name: "Jalaun", state: "Uttar Pradesh" },
  { no: 46, name: "Jhansi", state: "Uttar Pradesh" },
  { no: 47, name: "Hamirpur", state: "Uttar Pradesh" },
  { no: 48, name: "Banda", state: "Uttar Pradesh" },
  { no: 49, name: "Fatehpur", state: "Uttar Pradesh" },
  { no: 50, name: "Kaushambi", state: "Uttar Pradesh" },
  { no: 51, name: "Phulpur", state: "Uttar Pradesh" },
  { no: 52, name: "Allahabad", state: "Uttar Pradesh" },
  { no: 53, name: "Barabanki", state: "Uttar Pradesh" },
  { no: 54, name: "Faizabad", state: "Uttar Pradesh" },
  { no: 55, name: "Ambedkar Nagar", state: "Uttar Pradesh" },
  { no: 56, name: "Bahraich", state: "Uttar Pradesh" },
  { no: 57, name: "Kaisarganj", state: "Uttar Pradesh" },
  { no: 58, name: "Shrawasti", state: "Uttar Pradesh" },
  { no: 59, name: "Gonda", state: "Uttar Pradesh" },
  { no: 60, name: "Domriaganj", state: "Uttar Pradesh" },
  { no: 61, name: "Basti", state: "Uttar Pradesh" },
  { no: 62, name: "Sant Kabir Nagar", state: "Uttar Pradesh" },
  { no: 63, name: "Maharajganj", state: "Uttar Pradesh" },
  { no: 64, name: "Gorakhpur", state: "Uttar Pradesh" },
  { no: 65, name: "Kushi Nagar", state: "Uttar Pradesh" },
  { no: 66, name: "Deoria", state: "Uttar Pradesh" },
  { no: 67, name: "Bansgaon", state: "Uttar Pradesh" },
  { no: 68, name: "Lalganj", state: "Uttar Pradesh" },
  { no: 69, name: "Azamgarh", state: "Uttar Pradesh" },
  { no: 70, name: "Ghosi", state: "Uttar Pradesh" },
  { no: 71, name: "Salempur", state: "Uttar Pradesh" },
  { no: 72, name: "Ballia", state: "Uttar Pradesh" },
  { no: 73, name: "Jaunpur", state: "Uttar Pradesh" },
  { no: 74, name: "Machhlishahr", state: "Uttar Pradesh" },
  { no: 75, name: "Ghazipur", state: "Uttar Pradesh" },
  { no: 76, name: "Chandauli", state: "Uttar Pradesh" },
  { no: 77, name: "Varanasi", state: "Uttar Pradesh" },
  { no: 78, name: "Sant Ravi Das Nagar (Bhadohi)", state: "Uttar Pradesh" },
  { no: 79, name: "Mirzapur", state: "Uttar Pradesh" },
  { no: 80, name: "Robertsganj", state: "Uttar Pradesh" },
  { no: 1, name: "Tehri Garhwal", state: "Uttarakhand" },
  { no: 2, name: "Garhwal", state: "Uttarakhand" },
  { no: 3, name: "Almora", state: "Uttarakhand" },
  { no: 4, name: "Nainital - Udhamsingh Nagar", state: "Uttarakhand" },
  { no: 5, name: "Hardwar", state: "Uttarakhand" },
  { no: 1, name: "Koch Bihar", state: "West Bengal" },
  { no: 2, name: "Alipurduars", state: "West Bengal" },
  { no: 3, name: "Jalpaiguri", state: "West Bengal" },
  { no: 4, name: "Darjiling", state: "West Bengal" },
  { no: 5, name: "Raiganj", state: "West Bengal" },
  { no: 6, name: "Balurghat", state: "West Bengal" },
  { no: 7, name: "Maldah Uttar", state: "West Bengal" },
  { no: 8, name: "Maldah Dakshin", state: "West Bengal" },
  { no: 9, name: "Jangipur", state: "West Bengal" },
  { no: 10, name: "Baharampur", state: "West Bengal" },
  { no: 11, name: "Murshidabad", state: "West Bengal" },
  { no: 12, name: "Krishnanagar", state: "West Bengal" },
  { no: 13, name: "Ranaghat", state: "West Bengal" },
  { no: 14, name: "Bangaon", state: "West Bengal" },
  { no: 15, name: "Barakpur", state: "West Bengal" },
  { no: 16, name: "Dum Dum", state: "West Bengal" },
  { no: 17, name: "Barasat", state: "West Bengal" },
  { no: 18, name: "Basirhat", state: "West Bengal" },
  { no: 19, name: "Jaynagar", state: "West Bengal" },
  { no: 20, name: "Mathurapur", state: "West Bengal" },
  { no: 21, name: "Diamond Harbour", state: "West Bengal" },
  { no: 22, name: "Jadavpur", state: "West Bengal" },
  { no: 23, name: "Kolkata Dakshin", state: "West Bengal" },
  { no: 24, name: "Kolkata Uttar", state: "West Bengal" },
  { no: 25, name: "Haora", state: "West Bengal" },
  { no: 26, name: "Uluberiya", state: "West Bengal" },
  { no: 27, name: "Shrirampur", state: "West Bengal" },
  { no: 28, name: "Hugli", state: "West Bengal" },
  { no: 29, name: "Arambag", state: "West Bengal" },
  { no: 30, name: "Tamluk", state: "West Bengal" },
  { no: 31, name: "Kanthi", state: "West Bengal" },
  { no: 32, name: "Ghatal", state: "West Bengal" },
  { no: 33, name: "Jhargram", state: "West Bengal" },
  { no: 34, name: "Medinipur", state: "West Bengal" },
  { no: 35, name: "Puruliya", state: "West Bengal" },
  { no: 36, name: "Bankura", state: "West Bengal" },
  { no: 37, name: "Bishnupur", state: "West Bengal" },
  { no: 38, name: "Barddhaman Purba", state: "West Bengal" },
  { no: 39, name: "Barddhaman - Durgapur", state: "West Bengal" },
  { no: 40, name: "Asansol", state: "West Bengal" },
  { no: 41, name: "Bolpur", state: "West Bengal" },
  { no: 42, name: "Birbhum", state: "West Bengal" },
];

/** Constituencies grouped by state/UT (for grouped dropdowns). */
export const CONSTITUENCIES_BY_STATE: { state: string; items: Constituency[] }[] = (() => {
  const m = new Map<string, Constituency[]>();
  for (const c of CONSTITUENCIES) {
    if (!m.has(c.state)) m.set(c.state, []);
    m.get(c.state)!.push(c);
  }
  return [...m.entries()].map(([state, items]) => ({ state, items }));
})();

export const CONSTITUENCY_NAMES: string[] = CONSTITUENCIES.map((c) => c.name);

const BY_NAME = new Map(CONSTITUENCIES.map((c) => [c.name.toLowerCase(), c]));

/** True if `name` is an official constituency (case-insensitive). */
export function isKnownConstituency(name: string): boolean {
  return BY_NAME.has((name || "").trim().toLowerCase());
}

/** Resolve a free-text/name to its canonical constituency, or null. */
export function resolveConstituency(name: string): Constituency | null {
  return BY_NAME.get((name || "").trim().toLowerCase()) ?? null;
}

/** Dropdown label, e.g. "39 · Nawada". */
export function constituencyLabel(c: Constituency): string {
  return `${c.no} · ${c.name}`;
}
