"""add mp_allowlist table

Revision ID: 0e278c252d52
Revises: 39530dd936af
Create Date: 2026-07-03 22:01:46.483735

"""
from alembic import op
import sqlalchemy as sa


revision = '0e278c252d52'
down_revision = '39530dd936af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_allowlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_allowlist_email_hash'), 'mp_allowlist', ['email_hash'], unique=False)
    op.create_index(op.f('ix_mp_allowlist_phone_hash'), 'mp_allowlist', ['phone_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mp_allowlist_phone_hash'), table_name='mp_allowlist')
    op.drop_index(op.f('ix_mp_allowlist_email_hash'), table_name='mp_allowlist')
    op.drop_table('mp_allowlist')
    # ### end Alembic commands ###
