"""add audio_url and photo_url to complaints

Revision ID: 1e19cbbf7777
Revises: 0e278c252d52
Create Date: 2026-07-04 09:20:20.889815

"""
from alembic import op
import sqlalchemy as sa


revision = '1e19cbbf7777'
down_revision = '0e278c252d52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'photo_url')
    op.drop_column('complaints', 'audio_url')
    # ### end Alembic commands ###
