"""encrypt user PII fields, add profile columns

Revision ID: 39530dd936af
Revises: 9eb7d7a5fa6a
Create Date: 2026-07-03 20:51:38.041578

"""
from alembic import op
import sqlalchemy as sa


revision = '39530dd936af'
down_revision = '9eb7d7a5fa6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('email_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('phone_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('display_name_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('first_name_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('last_name_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('address_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('constituency_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('pincode_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('state_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('aadhaar_last4', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=False)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_column('users', 'aadhaar_last4')
    op.drop_column('users', 'state_encrypted')
    op.drop_column('users', 'pincode_encrypted')
    op.drop_column('users', 'constituency_encrypted')
    op.drop_column('users', 'address_encrypted')
    op.drop_column('users', 'last_name_encrypted')
    op.drop_column('users', 'first_name_encrypted')
    op.drop_column('users', 'display_name_encrypted')
    op.drop_column('users', 'phone_hash')
    op.drop_column('users', 'phone_encrypted')
    op.drop_column('users', 'email_hash')
    op.drop_column('users', 'email_encrypted')
    # ### end Alembic commands ###
