"""add constituency to complaints and mp_allowlist

Revision ID: 5f3866c03df8
Revises: 1e19cbbf7777
Create Date: 2026-07-04 10:49:48.411810

"""
from alembic import op
import sqlalchemy as sa


revision = '5f3866c03df8'
down_revision = '1e19cbbf7777'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('constituency', sa.String(), nullable=True))
    op.create_index(op.f('ix_complaints_constituency'), 'complaints', ['constituency'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'users', ['user_id'], ['id'])
    op.add_column('mp_allowlist', sa.Column('constituency', sa.String(), nullable=True))
    op.create_index(op.f('ix_mp_allowlist_constituency'), 'mp_allowlist', ['constituency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mp_allowlist_constituency'), table_name='mp_allowlist')
    op.drop_column('mp_allowlist', 'constituency')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_constituency'), table_name='complaints')
    op.drop_column('complaints', 'constituency')
    op.drop_column('complaints', 'user_id')
    # ### end Alembic commands ###
