"""add gov_education_stats table and mp district field

Revision ID: 8f646de7425b
Revises: 5f3866c03df8
Create Date: 2026-07-04 12:10:31.082272

"""
from alembic import op
import sqlalchemy as sa


revision = '8f646de7425b'
down_revision = '5f3866c03df8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gov_education_stats',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('schools_total', sa.Integer(), nullable=True),
    sa.Column('students_total', sa.Integer(), nullable=True),
    sa.Column('pass_pct_class_x', sa.Float(), nullable=True),
    sa.Column('pass_pct_class_xii', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('district')
    )
    op.add_column('mp_allowlist', sa.Column('district', sa.String(), nullable=True))
    op.create_index(op.f('ix_mp_allowlist_district'), 'mp_allowlist', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mp_allowlist_district'), table_name='mp_allowlist')
    op.drop_column('mp_allowlist', 'district')
    op.drop_table('gov_education_stats')
    # ### end Alembic commands ###
